# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\Miniconda3-x64"

  matrix:
      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "2.7"

platform:
    -x64

install:
    - "if not exist \"%userprofile%\\.config\\yt\" mkdir %userprofile%\\.config\\yt"
    - "echo [yt] > %userprofile%\\.config\\yt\\ytrc"
    - "echo suppressStreamLogging = True >> %userprofile%\\.config\\yt\\ytrc"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    # Create a conda environment
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install -q --yes -c conda-forge numpy scipy nose setuptools ipython Cython sympy fastcache h5py matplotlib flake8 mock"
    - "pip install -e ."

# Not a .NET project
build: false

test_script:
  - "nosetests --nologcapture -sv yt"
